spring:
  datasource:
    username: postgres
    password: postgres
    url: jdbc:postgresql://qr_management_microservice_db:5432/qr_management_db
  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://qr_management_microservice_db:5432/qr_management_db

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: user
    password: password

jwt:
  keys:
    public:
      path: keys/publicSortlyQR.pem

server:
  port: 8080